CREATE TABLE `images` (
	`source_md5` CHAR(32) NOT NULL,
	`source` VARCHAR(1000) NOT NULL,
	`state` ENUM('LOADING','FAILURE','SUCCESS') NOT NULL DEFAULT 'FAILURE',
	`ts` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	`filename` CHAR(50) NULL DEFAULT NULL,
	PRIMARY KEY (`source_md5`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;
